<?php

namespace App\Modules\Students\Actions\Mistakes;

use App\Modules\Academic\Models\ExamAttempt;
use App\Modules\Academic\Models\ExamAttemptAnswer;
use App\Modules\Students\Models\MistakeItem;
use Illuminate\Support\Collection;

class SyncExamAttemptMistakesAction
{
    public function execute(ExamAttempt $examAttempt): void
    {
        $examAttempt->loadMissing([
            'exam.lecture',
            'answers.question.choices',
        ]);

        /** @var Collection<int, ExamAttemptAnswer> $answers */
        $answers = $examAttempt->answers->keyBy('question_id');

        foreach ($answers as $questionId => $answer) {
            $questionReference = 'question-'.$questionId;
            $isAutoGenerated = [
                'student_id' => $examAttempt->student_id,
                'exam_id' => $examAttempt->exam_id,
                'question_reference' => $questionReference,
                'source' => 'exam_attempt',
            ];

            if ($answer->is_correct) {
                MistakeItem::query()->where($isAutoGenerated)->delete();

                continue;
            }

            if ($answer->selected_answer === null || $answer->selected_answer === '') {
                MistakeItem::query()->where($isAutoGenerated)->delete();

                continue;
            }

            MistakeItem::query()->updateOrCreate(
                $isAutoGenerated,
                [
                    'lecture_id' => $examAttempt->exam?->lecture_id,
                    'question_text' => $answer->answer_meta['question_prompt'] ?? $answer->question?->prompt,
                    'correct_answer_snapshot' => $answer->answer_meta['correct_choice_content'] ?? null,
                    'model_answer_snapshot' => $answer->answer_meta['explanation'] ?? $answer->answer_meta['correct_choice_content'] ?? null,
                    'explanation' => $answer->answer_meta['explanation'] ?? $answer->question?->explanation,
                    'image_path' => null,
                    'score_lost' => max(0, (int) $answer->max_score - (int) ($answer->awarded_score ?? 0)),
                    'score_meta' => [
                        'awarded_score' => (int) ($answer->awarded_score ?? 0),
                        'max_score' => (int) $answer->max_score,
                    ],
                    'meta' => [
                        'exam_attempt_id' => $examAttempt->id,
                        'question_id' => $questionId,
                    ],
                ],
            );
        }
    }
}
