<?php

return [
    'brand' => [
        'name' => 'منصة الإتقان التعليمية',
        'teacher_name' => 'أ. أحمد الفيزياء',
        'tagline' => 'منصة تعليمية عربية لإدارة التعلّم، الحضور، المشتريات، والدعم في تجربة واحدة متماسكة.',
        'support_phone' => '+20 100 000 0000',
        'support_whatsapp' => '+20 100 000 0000',
    ],

    'public' => [
        'hero_badge' => 'منصة عربية أولًا لطلاب الثانوية',
        'hero_title' => 'تعلّم منظم، متابعة أوضح، وتجربة طالب عملية من أول محاضرة حتى آخر مراجعة.',
        'hero_description' => 'منصة أستاذ واحد تجمع الشرح، الباقات، الكتب، المتابعة، وسجل الطالب داخل واجهة عربية واضحة ومباشرة.',
        'video' => [
            'title' => 'رسالة المعلم',
            'description' => 'جولة سريعة في أسلوب الشرح، خطة المتابعة، وكيف يستفيد الطالب من المنصة.',
            'embed_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        ],
        'features' => [
            ['title' => 'شرح ومراجعات', 'description' => 'تنظيم واضح للمحتوى والباقات بما يناسب رحلة الطالب الفعلية.'],
            ['title' => 'حضور وسجل طالب', 'description' => 'ربط بين السنتر والبوابة وسجل الأداء والمتابعة المستقبلية.'],
            ['title' => 'كتب وطلبات', 'description' => 'إبراز الكتب والطلبات وسجل الشراء في مكان واحد قابل للتوسع.'],
            ['title' => 'دعم مباشر', 'description' => 'قناة واضحة للشكاوى والاقتراحات والتواصل الفني عند الحاجة.'],
        ],
        'achievers' => [
            ['name' => 'سارة محمد', 'achievement' => 'تفوقت في الاختبارات الشهرية بعد انتظام 8 أسابيع.', 'score' => '98%'],
            ['name' => 'يوسف خالد', 'achievement' => 'رفع مستواه في المسائل المعقدة عبر خطة مراجعة مركزة.', 'score' => '95%'],
            ['name' => 'ملك أحمد', 'achievement' => 'استفادت من الدمج بين السنتر والبوابة وسجل الأخطاء.', 'score' => '99%'],
        ],
        'social_links' => [
            ['label' => 'YouTube', 'url' => 'https://youtube.com'],
            ['label' => 'Facebook', 'url' => 'https://facebook.com'],
            ['label' => 'Telegram', 'url' => 'https://t.me'],
        ],
        'footer_links' => [
            ['label' => 'الرئيسية', 'route' => 'welcome'],
            ['label' => 'تسجيل الطالب', 'route' => 'student.register'],
            ['label' => 'دخول الطالب', 'route' => 'student.login'],
            ['label' => 'دخول الإدارة', 'route' => 'admin.login'],
        ],
        'support' => [
            'title' => 'هل تحتاج مساعدة؟',
            'description' => 'فريق المتابعة جاهز للرد على الاستفسارات التقنية والتنظيمية بسرعة.',
            'cta_label' => 'تواصل مع الدعم',
        ],
    ],

    'roles' => [
        'Super Admin' => ['*'],
        'Operations Manager' => [
            'dashboard.view',
            'students.view',
            'students.manage',
            'students.assign',
            'centers.view',
            'centers.manage',
            'attendance.view',
            'attendance.manage',
            'reports.view',
            'complaints.view',
            'complaints.manage',
        ],
        'Academic Manager' => [
            'dashboard.view',
            'grades.view',
            'grades.manage',
            'tracks.view',
            'tracks.manage',
            'content.view',
            'content.manage',
            'questions.view',
            'questions.manage',
            'exams.view',
            'exams.manage',
            'packages.view',
            'packages.manage',
            'books.view',
            'books.manage',
            'mistakes.view',
        ],
        'Content Editor' => [
            'dashboard.view',
            'content.view',
            'content.manage',
            'questions.view',
            'questions.manage',
            'mistakes.view',
        ],
        'Student Affairs' => [
            'dashboard.view',
            'students.view',
            'students.manage',
            'students.impersonate',
            'forum.view',
            'forum.manage',
            'complaints.view',
            'complaints.manage',
            'mistakes.view',
            'mistakes.manage',
        ],
        'Finance Officer' => [
            'dashboard.view',
            'orders.view',
            'orders.manage',
            'transactions.view',
            'transactions.manage',
            'shipping.view',
            'shipping.manage',
            'entitlements.view',
            'entitlements.manage',
            'exports.run',
            'books.view',
        ],
        'Support Agent' => [
            'dashboard.view',
            'tickets.view',
            'tickets.manage',
            'complaints.view',
            'complaints.manage',
            'forum.view',
            'forum.manage',
            'forum.reply',
        ],
        'Center Supervisor' => [
            'dashboard.view',
            'centers.view',
            'attendance.view',
            'attendance.manage',
        ],
        'Payroll Officer' => [
            'dashboard.view',
            'payroll.view',
            'payroll.manage',
        ],
    ],

    'permissions' => [
        'dashboard.view',
        'settings.view',
        'settings.manage',
        'audit-logs.view',
        'admins.view',
        'admins.manage',
        'grades.view',
        'grades.manage',
        'tracks.view',
        'tracks.manage',
        'students.view',
        'students.manage',
        'students.assign',
        'students.impersonate',
        'content.view',
        'content.manage',
        'questions.view',
        'questions.manage',
        'exams.view',
        'exams.manage',
        'packages.view',
        'packages.manage',
        'books.view',
        'books.manage',
        'orders.view',
        'orders.manage',
        'transactions.view',
        'transactions.manage',
        'shipping.view',
        'shipping.manage',
        'entitlements.view',
        'entitlements.manage',
        'centers.view',
        'centers.manage',
        'attendance.view',
        'attendance.manage',
        'complaints.view',
        'complaints.manage',
        'forum.view',
        'forum.manage',
        'forum.reply',
        'tickets.view',
        'tickets.manage',
        'reports.view',
        'exports.run',
        'payroll.view',
        'payroll.manage',
        'mistakes.view',
        'mistakes.manage',
    ],

    'admin_menu' => [
        [
            'label' => 'لوحة التحكم',
            'items' => [
                ['label' => 'الرئيسية', 'route' => 'admin.dashboard', 'permission' => 'dashboard.view'],
                ['label' => 'سجل المراجعة', 'route' => 'admin.audit-logs.index', 'permission' => 'audit-logs.view'],
            ],
        ],
        [
            'label' => 'الإدارة والحَوْكمة',
            'items' => [
                ['label' => 'المشرفون', 'route' => 'admin.admins.index', 'permission' => 'admins.view'],
                ['label' => 'الإعدادات', 'route' => 'admin.settings.index', 'permission' => 'settings.view'],
            ],
        ],
        [
            'label' => 'الأكاديمي والطلاب',
            'items' => [
                ['label' => 'الصفوف', 'route' => 'admin.grades.index', 'permission' => 'grades.view'],
                ['label' => 'المسارات', 'route' => 'admin.tracks.index', 'permission' => 'tracks.view'],
                ['label' => 'أقسام المنهج', 'route' => 'admin.curriculum-sections.index', 'permission' => 'content.view'],
                ['label' => 'أقسام المحاضرات', 'route' => 'admin.lecture-sections.index', 'permission' => 'content.view'],
                ['label' => 'المحتوى الأكاديمي', 'route' => 'admin.lectures.index', 'permission' => 'content.view'],
                ['label' => 'الاختبارات', 'route' => 'admin.exams.index', 'permission' => 'exams.view'],
                ['label' => 'محاولات الاختبارات', 'route' => 'admin.exam-attempts.index', 'permission' => 'exams.view'],
                ['label' => 'الطلاب', 'route' => 'admin.students.index', 'permission' => 'students.view'],
                ['label' => 'مركز الأخطاء', 'route' => 'admin.mistakes.index', 'permission' => 'mistakes.view'],
            ],
        ],
        [
            'label' => 'التشغيل والمتابعة',
            'items' => [
                ['label' => 'السناتر', 'route' => 'admin.centers.index', 'permission' => 'centers.view'],
                ['label' => 'تقارير الحضور', 'route' => 'admin.attendance.index', 'permission' => 'attendance.view'],
                ['label' => 'الشكاوى والاقتراحات', 'route' => 'admin.complaints.index', 'permission' => 'complaints.view'],
            ],
        ],
        [
            'label' => 'التجارة والدعم',
            'items' => [
                ['label' => 'الباقات', 'route' => 'admin.packages.index', 'permission' => 'packages.view'],
                ['label' => 'الكتب', 'route' => 'admin.books.index', 'permission' => 'books.view'],
                ['label' => 'الطلبات', 'route' => 'admin.orders.index', 'permission' => 'orders.view'],
                ['label' => 'ملتقى الأسئلة', 'route' => 'admin.forum-threads.index', 'permission' => 'forum.view'],
            ],
        ],
    ],

    'student_menu' => [
        ['label' => 'الرئيسية', 'route' => 'student.dashboard'],
        ['label' => 'المحاضرات', 'route' => 'student.lectures.index'],
        ['label' => 'الباقات', 'route' => 'student.packages.index'],
        ['label' => 'كتب', 'route' => 'student.books.index'],
        ['label' => 'ملتقى الأسئلة', 'route' => 'student.forum.index'],
        ['label' => 'أخطائي', 'route' => 'student.mistakes.index'],
    ],
];
