<?php

return [
    'brand' => [
        'name' => 'منصة الإتقان التعليمية',
        'teacher_name' => 'أ. فيزياء',
        'tagline' => 'منصة تشغيل تعليمية عربية لإدارة التعلم والحضور والمبيعات والدعم.',
        'support_phone' => '+20 100 000 0000',
        'support_whatsapp' => '+20 100 000 0000',
    ],

    'roles' => [
        'Super Admin' => ['*'],
        'Operations Manager' => [
            'dashboard.view',
            'students.view',
            'students.manage',
            'students.assign',
            'centers.view',
            'centers.manage',
            'attendance.view',
            'attendance.manage',
            'reports.view',
            'complaints.view',
            'complaints.manage',
        ],
        'Academic Manager' => [
            'dashboard.view',
            'grades.view',
            'grades.manage',
            'tracks.view',
            'tracks.manage',
            'content.view',
            'content.manage',
            'questions.view',
            'questions.manage',
            'exams.view',
            'exams.manage',
            'packages.view',
            'packages.manage',
        ],
        'Content Editor' => [
            'dashboard.view',
            'content.view',
            'content.manage',
            'questions.view',
            'questions.manage',
        ],
        'Student Affairs' => [
            'dashboard.view',
            'students.view',
            'students.manage',
            'students.impersonate',
            'forum.view',
            'forum.manage',
            'complaints.view',
            'complaints.manage',
        ],
        'Finance Officer' => [
            'dashboard.view',
            'orders.view',
            'orders.manage',
            'transactions.view',
            'transactions.manage',
            'shipping.view',
            'shipping.manage',
            'entitlements.view',
            'entitlements.manage',
            'exports.run',
        ],
        'Support Agent' => [
            'dashboard.view',
            'tickets.view',
            'tickets.manage',
            'complaints.view',
            'complaints.manage',
            'forum.reply',
        ],
        'Center Supervisor' => [
            'dashboard.view',
            'centers.view',
            'attendance.view',
            'attendance.manage',
        ],
        'Payroll Officer' => [
            'dashboard.view',
            'payroll.view',
            'payroll.manage',
        ],
    ],

    'permissions' => [
        'dashboard.view',
        'settings.view',
        'settings.manage',
        'audit-logs.view',
        'admins.view',
        'admins.manage',
        'grades.view',
        'grades.manage',
        'tracks.view',
        'tracks.manage',
        'students.view',
        'students.manage',
        'students.assign',
        'students.impersonate',
        'content.view',
        'content.manage',
        'questions.view',
        'questions.manage',
        'exams.view',
        'exams.manage',
        'packages.view',
        'packages.manage',
        'orders.view',
        'orders.manage',
        'transactions.view',
        'transactions.manage',
        'shipping.view',
        'shipping.manage',
        'entitlements.view',
        'entitlements.manage',
        'centers.view',
        'centers.manage',
        'attendance.view',
        'attendance.manage',
        'complaints.view',
        'complaints.manage',
        'forum.view',
        'forum.manage',
        'forum.reply',
        'tickets.view',
        'tickets.manage',
        'reports.view',
        'exports.run',
        'payroll.view',
        'payroll.manage',
    ],

    'admin_menu' => [
        [
            'label' => 'لوحة التحكم',
            'items' => [
                ['label' => 'الرئيسية', 'route' => 'admin.dashboard', 'permission' => 'dashboard.view'],
                ['label' => 'سجل المراجعة', 'route' => 'admin.audit-logs.index', 'permission' => 'audit-logs.view'],
            ],
        ],
        [
            'label' => 'الإدارة والحوكمة',
            'items' => [
                ['label' => 'المشرفون', 'route' => 'admin.admins.index', 'permission' => 'admins.view'],
                ['label' => 'الإعدادات', 'route' => 'admin.settings.index', 'permission' => 'settings.view'],
            ],
        ],
        [
            'label' => 'الأكاديمي',
            'items' => [
                ['label' => 'الصفوف', 'route' => 'admin.grades.index', 'permission' => 'grades.view'],
                ['label' => 'المسارات', 'route' => 'admin.tracks.index', 'permission' => 'tracks.view'],
            ],
        ],
    ],

    'student_menu' => [
        ['label' => 'الرئيسية', 'href' => '#'],
        ['label' => 'المحاضرات', 'href' => '#'],
        ['label' => 'الباقات', 'href' => '#'],
        ['label' => 'كتب', 'href' => '#'],
        ['label' => 'ملتقى الأسئلة', 'href' => '#'],
        ['label' => 'أخطائي', 'href' => '#'],
    ],
];
